FROM node:18-alpine as build

WORKDIR /app

COPY . .

RUN ls -al

RUN npm install
RUN npm run build

FROM nginx:alpine

COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 8080

CMD ["nginx", "-g", "daemon off;"]
