FROM node:18-alpine as build

WORKDIR /app

COPY . .

RUN ls -al

RUN npm install
RUN npm run build

FROM nginx:alpine

CMD envsubst '$NGINX_EXPOSE_PORT $SERVER_API_PORT' < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf && nginx -g 'daemon off;'

COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE $NGINX_EXPOSE_PORT
