FROM node:18-alpine as build

WORKDIR /app

COPY . .

RUN ls -al

RUN npm install
RUN npm run build

FROM nginx:alpine

CMD envsubst '$SERVER_API_PORT $LOCAL_PRIVKEY_LOCATION $NGINX_PRIVKEY_LOCATION $LOCAL_FULLCHAIN_LOCATION $NGINX_FULLCHAIN_LOCATION' < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf && nginx -g 'daemon off;'
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80 443
