version: '3'
services:
  client:
    container_name: musigaero-client
    build:
      context: ./client
      dockerfile: Dockerfile-client
    restart: unless-stopped
    env_file:
      - .env
    ports:
        - "$NGINX_EXPOSE_PORT:$NGINX_EXPOSE_PORT"
    volumes:
        - "./nginx/nginx.conf.template:/etc/nginx/nginx.conf.template"
      
      
  server:
    container_name: musigaero-server
    build:
      context: .
      dockerfile: server/Dockerfile-server
    env_file:
      - .env
    restart: unless-stopped
    command: npm run start
    ports:
        - "$SERVER_API_PORT:$SERVER_API_PORT"
    depends_on:
      - db

  db:
    container_name: musigaero-mysql
    image: mysql:8.0.29
    volumes:
      - './database/mysql/data:/var/lib/mysql'
      - './database/mysql/securefile:/data/securefile'
    restart: 'unless-stopped'
    env_file:
      - .env
    ports:
      - $MYSQL_SERVER_PORT:$MYSQL_CONNECT_PORT
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
